### ISSUE TITLE
Intermittent 'Excess padding' Error on windows app for transfer sender

### ISSUE THREAD

**Issue by tomt1664** [layer2tech/mercury-wallet#80] opened 2021-02-26 16:02 UTC

**Comment by 86667** [comment] 2021-03-15 09:24
Couldnt reproduce. Will keep open for a while incase someone comes across this again. Paste client and server logs in this thread.

**Comment by 86667** [comment] 2021-04-29 10:20
Seems to have been fixed. Closing.

**Closed by 86667** 2021-04-29 10:20 UTC
Labels: bug
